#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

symlinks::apply() {
  local -r CONFIG="$DOTFILES_PATH/symlinks/$1"
  shift

  echo
  "$DOTLY_PATH/modules/dotbot/bin/dotbot" -d "$DOTFILES_PATH" -c "$CONFIG" "$@"
  echo
}

##? Apply all symlinks
##?
##? Usage:
##?    apply
##?

symlinks::apply "conf.yaml"

if platform::is_macos; then
  symlinks::apply "conf.macos.yaml"

  sudo ln -sf "$DOTFILES_PATH/os/mac/plist/limit.maxfiles.plist" "/Library/LaunchDaemons/limit.maxfiles.plist"
  sudo ln -sf "$DOTFILES_PATH/os/mac/plist/limit.maxproc.plist" "/Library/LaunchDaemons/limit.maxproc.plist"
  sudo chmod 644 "/Library/LaunchDaemons/limit.maxfiles.plist"
  sudo chmod 644 "/Library/LaunchDaemons/limit.maxproc.plist"
  sudo chown root:wheel /Library/LaunchDaemons/limit.maxfiles.plist
  sudo chown root:wheel /Library/LaunchDaemons/limit.maxproc.plist
  sudo launchctl load -w "/Library/LaunchDaemons/limit.maxfiles.plist"
  sudo launchctl load -w "/Library/LaunchDaemons/limit.maxproc.plist"
else
  symlinks::apply "conf.linux.yaml"
fi

log::success "Done!"
