#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTLY_PATH/scripts/self/utils/update.sh"

##? Updates submodules, dotfiles and attempts to do some setup
#?? 1.0.0
##?
##? Usage:
##?    update

docs::eval_help "$@"

#log::note "Closing Apps"
#killall Rocket || true

log::note "Updating dotfiles"
self_update

log::note "Updating submodules"
update_submodules

# @todo Backup if exists before
log::note "Setting up Symlinks"
dot symlinks apply 2>&1

#log::note "Opening apps"
#open /Applications/Rocket.app
